# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    image: "postgres:14.1"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=task-bunny
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql

  back-end:
    image: task-bunny-app:latest
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      - spring.datasource.url=jdbc:postgresql://localhost:5432/task-bunny

#  front-end:
#    image: task-bunny-web:latest
#    depends_on:
#      - back-end
#    ports:
#      - 4200:80